### ISSUE TITLE
Unificar cajas de listado de usados / busqueda

### ISSUE THREAD

**Issue by lennonprado** [sil22/DonFranciscoMaquinarias#11]
La caja que contiene los elementos de la busqueda deberia ser igual a las cajas que los principales. "Mas detalle" deberia llamarse "Mas información". El titulo no deberia tener fondo amarillo. Cada card tiene un borde gris, etc. La imagen no tiene bordes redondeados. La distribución continuaria igual, imagen a la izquierda, texto a la derecha.

**Comment by sil22** [comment]
Marce, te referis a que  la caja que te mando en la screenshot, sea una
card como las de featuredCars?

**Comment by lennonprado** [comment]
Claro. Debería ser parecida a los destacados. Pero a lo ancho. Imagen a la izquierda y textos a la derecha pero con los mismos estilos.

**Comment by sil22** [comment]
Perfecto! Queria corroborar si habia entendido bien! Gracias!

2017-11-28 18:39 GMT-03:00 Marcelo Prado <notifications@github.com>:

**Comment by silvinamunoz** [comment]
*Ingredientes para 2 tartas grandes:*
• 400 g de harina integral super fina
• 80 ml de aceite de oliva
• opcional: 5 cdas de mix de semillas peladas crudas (girasol, lino, sésamo)
• 180- 200 ml de agua
• 10 g de sal
