### ISSUE TITLE
[Contacto]

### ISSUE THREAD

**Issue by lennonprado** [sil22/DonFranciscoMaquinarias#14]
Hay un error que muestra parte del mensaje como un comentario http://prntscr.com/he79su

**Comment by sil22** [comment]
No lo puedo reproducir a este issue.. Inclusive lo veo con otro formato de letra en la screenshot q me pasaste.. 
https://prnt.sc/hi8siy

**Comment by lennonprado** [comment]
Lo checkeo de nuevo en la oficina y te digo. Si se fue, lo cierro.

**Comment by lennonprado** [comment]
ya detecte que es ese problema y aparece en varios lados. al parecer no le gusta que los bloques php no aparezcan sin la palabrita php. Solucion: cambiar <? por <?php por ejemplo en este caso http://prntscr.com/hixx1i Pasa en varios lados esto. en destacados por ejemplo y algun otro por ahi.

**Comment by sil22** [comment]
lo cerre sin querer marce! fijate si seguis viendo el error.. porque yo probe chrome, en incognito, en mozilla y no lo pude ver. Avisame, gracias!
