### ISSUE TITLE
Cambio botones destacados

### ISSUE THREAD

**Issue by lennonprado** [sil22/DonFranciscoMaquinarias#2]
Pondria dos botones en lugar del "ver mas" actual. 

Uno donde te abra el modal por ahora llamemosle "Más imágenes" y muestre todas las imagenes de esa unidad dentro del modal y otro button que seria el ver "Más información" y te lleve a la unidad.

**Comment by sil22** [comment]
chequear si esta bien el estilo y ubicacion de los botones. Aun no esta con funcionalidad 100% el button "Mas imagenes".
