### ISSUE TITLE
Usados seleccionados con menos elementos

### ISSUE THREAD

**Issue by lennonprado** [sil22/DonFranciscoMaquinarias#3]
En usados seleccionados se ven repetidas las unidades, no se si me pasa a mi solo. 
Esta bien el carousel, pondria 3 paneles nomas de 8 elementos cada una. 
Quizas convenga ponerle un limit 24 a la consulta para que no te traiga mas elementos.

**Comment by sil22** [comment]
No te pasa a vos, esta sin terminar el carousel por eso se carga con todas las imagenes.
No podia hacerlo andar con 3 imagenes, hasta que pude y no logre terminarlo.
Pruebo con lo que me decis
